spring:
  application:
    name: lavajatoapi
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:lavajatoapi
    driverClassName: org.h2.Driver
    username: sa
    password: admin
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect